Small cleanups
open-io/ansible-role-openio-gridinit pull request #5
Opened 2018-03-08 13:43 UTC by vincent-legoll

2018-03-14 14:28 UTC, cdelgehier requested changes
Rollback `ansible-role-openio-repository` and it s good

2018-03-14 14:28 UTC, cdelgehier commented on README.md
> +- You have to use this role after the role `ansible-role-repo-openio-sds` (like [this](https://github.com/open-io/ansible-role-openio-gridinit/blob/docker-tests/test.yml#L7))
Wrong name
https://github.com/open-io/ansible-role-openio-repository

2018-03-14 14:28 UTC, cdelgehier commented on README.md
> +[all]
Not really a best practice

2018-03-14 14:45 UTC, vincent-legoll commented on README.md
> +- You have to use this role after the role `ansible-role-repo-openio-sds` (like [this](https://github.com/open-io/ansible-role-openio-gridinit/blob/docker-tests/test.yml#L7))
Yep you're right

2018-03-14 14:46 UTC, vincent-legoll commented on README.md
> +[all]
It was so that it is the same as the group the playbook is applied to...

2018-03-21 20:30 UTC, vincent-legoll commented
ping

2018-03-28 15:18 UTC, merged